### ISSUE TITLE
Wacom Intuos S scrolling does not work with pad buttons

### ISSUE THREAD

**Issue by LukeLR** [linuxwacom/xf86-input-wacom#111]
I want to use scrolling when pressing a pad button and moving the pen up or down. When using a stylus button, scrolling works by setting `xsetwacom set 14 Button 2 pan`. However, when trying to bind the `pan` action to a pad button by setting `xsetwacom set 15 Button 2 pan`, nothing happens. 

Is this a design limitation?

**Comment by Pinglinux** [comment]
No new features will be added to xf86-input-wacom. Please contribute to libinput.
