### ISSUE TITLE
Unable to install - bash: ./configure: No such file or directory Build Failed

### ISSUE THREAD

**Issue by tigerstripes175** [linuxwacom/xf86-input-wacom#114]
I tried both build from source, and 'get the drivers,' both failed with the same message
bash: ./configure: No such file or directory
Build Failed

I heard that if I change sudo make install to sudo checkinstall, however it didnt make a difference. I have tried a couple different things, all resulted in the same message.
I am using ubuntu 18.04.4, if that helps.

**Comment by whot** [comment]
you need to run `./autogen.sh` first (or `autoreconf` manually)
