### ISSUE TITLE
Only able to access one screen at a time.

### ISSUE THREAD

**Issue by coreyryanhanson** [linuxwacom/xf86-input-wacom#116]
I am running Centos 8 and I have been unable to map my Wacom Intuos Pro to both monitors simultaneously.  I'm not sure why, but I'm forced to toggle between them entirely on an individual basis which has never happened on my older Centos 7 system. I've included some relevant hardware info, please let me know if I should add anything else.

xorg-x11-drv-wacom version: 0.36.1
NVIDIA driver version-  440.82 (installed via EL-repo)
The GPU is a GeForce RTX 2080

and the two displays are
AU Optronics Corporation (DP-2), - 1920 x 1080 res
Ancor Communications Inc PA248 (HDMI-0) 1920 x 1200 res

**Comment by jigpu** [comment]
A few questions:
* Are you running CentOS 8.0 or 8.1 according to `cat /etc/redhat-release`?
* Are you running "CentOS Stream"?
* Are you running `xsetwacom set <id> MapToOutput next` to toggle displays, or another mechanism (and which)?

**Comment by coreyryanhanson** [comment]
Actually, I just tried enabling CentOS Stream and that did the trick. Thanks!!!!!!!
