### ISSUE TITLE
xsetwacom says "Button: Actions are not supported by xorg.conf.", but they are!

### ISSUE THREAD

**Issue by MPvHarmelen** [linuxwacom/xf86-input-wacom#122]
## Issue
The example shown in [this wiki article written for Xorg 1.10](https://github.com/linuxwacom/xf86-input-wacom/wiki/xorg.conf.d#example-dependent-device-static-configuration) includes several entries for changing the buttons, all with the following layout:

```
Option "Button<button number>" "<button action number>"
```
which work under Xorg 1.20.8 (detailed version below) and are also [documented](http://manpages.ubuntu.com/manpages/focal/en/man4/wacom.4.html) (search for `ButtonM`), but `xsetwacom -x get <device id> button <button number>`  or `xsetwacom -x get <device id> all` say:
```
Button: Actions are not supported by xorg.conf. Try shell format (-s) instead.
```

## Xorg version
```
X.Org X Server 1.20.8
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-177-generic x86_64 Ubuntu
Current Operating System: Linux <machine name> 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.4.0-31-generic root=UUID=<some id> ro quiet splash resume=/dev/<some partition> vt.handoff=7
Build Date: 06 April 2020  09:39:29AM
xorg-server 2:1.20.8-2ubuntu2 (For technical support please see http://www.ubuntu.com/support)
Current version of pixman: 0.38.4
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

## `setxwacom` source
https://github.com/linuxwacom/xf86-input-wacom/blob/master/tools/xsetwacom.c

## `man wacom`
```
Option "ButtonM" "AC"
    reports an action AC when button M is pressed,  where M is one of the device supported  button numbers,  it can be 1 to 32. Wacom uses a driver-internal button mapping, where any  physi‐
    cal  button  appears to the X server as the button specified by the ButtonM mapping. Hence, if two physical buttons have the same ButtonM mapping, the server will think they are the same
    physical button.  The default action reported to the X server is mouse button M click. Because X uses buttons 4, 5, 6, and 7 as the four scrolling  directions,  physical  buttons  4  and
    higher  are  mapped  to 8 and higher by default.  Only simple button presses can be configured here; for more complex actions, use xsetwacom(1).  To ignore the button click, i.e., to not
    report any button click event to the X server,  use "0" or "button 0".
```

**Comment by whot** [comment]
"button actions" in the driver refer to more complex settings, specifically the ability to send key strokes in response to a button press. These aren't configurable in the xorg.conf and since they're the prime use-case for button mappings on tablet pads xsetwacom somewhat "optimises" for that use-case.

You can remap buttons, sure, but in most cases that just has very little effect on a pad unless you're happy with the default left/middle/right mappings that most clients support.

So, fixable, but this is a cosmetic issue only IMO.
