### ISSUE TITLE
xsetwacom returns 0 even when there's an error

### ISSUE THREAD

**Issue by maruseu** [linuxwacom/xf86-input-wacom#126]
xsetwacom only seems to return a non zero when its run with absolutely no arguments

```
$ xsetwacom --set "Wacom Intuos S Pen stylus" Area 0 0 0 && echo success || echo failure
'Area' requires exactly 4 value(s).
success
```

**Comment by jigpu** [comment]
Looks like there are a few error paths that need to be updated...

**Comment by AstroLad47** [comment]
This is a fairly major task. I started to patch a version for my own use. After fixing get() and set() and still seeing the same problem, I looked deeper and discovered that many (most???) of the functions do not return status.They print to STDERR, but don't return an error code to the caller.

**Comment by Joshua-Dickens** [comment]
This should be fully fixed with the commits above and return error codes properly.
