### ISSUE TITLE
Cannot set button action via xorg.conf

### ISSUE THREAD

**Issue by rnoennig** [linuxwacom/xf86-input-wacom#127]
How should xorg.conf look like to set the button actions for the wacom pad buttons?

They can be properly configured either by
`xsetwacom set "Wacom Intuos Pro M Pad pad"  Button 3 "key e"`
or 
`xinput set-prop "Wacom Intuos Pro M Pad pad" "Wacom button action 2" "1114138, 65562" # key press 'e'`

But they will only last until next hotplug or reboot.
I'd like to have a permanent setup, which should be possible using xorg and the InputClass, right?

This is what my config looks like, the button stuff isn't working yet:

    Section "InputClass"
        Identifier "Wacom Intuos Pro M Pen Map to output"
        MatchProduct "Wacom"
        MatchProduct "Pen"
        # Map to output of first of three screens
        Option "TransformationMatrix" "0.333333 0 0 0 1 0 0 0 1"
    EndSection
    
    Section "InputClass"
        Identifier "Wacom Intuos Pro M Pad Button map"
        MatchProduct "Wacom"
        MatchProduct "Pad"
    
        # >>> AC_KEY=0x00010000;AC_KEYBTNPRESS=0x00100000;"%i, %i" % (AC_KEY | AC_KEYBTNPRESS | 26, AC_KEY | 26)
        # key e - switches to erase in krita
        Option "Wacom button action 2" "1114138, 65562"
        Option "button 2 action" "1114138, 65562"
        Option "button action 2" "1114138, 65562"
        Option "Wacom button action 3" "1114138, 65562"
        Option "button 3 action" "1114138, 65562"
        Option "button action 3" "1114138, 65562"
    EndSection

**Comment by jigpu** [comment]
Unfortunately, button actions are not supported by the xorg.conf.d syntax. You will need to create a script that runs on login which contains your xsetwacom commands.
