### ISSUE TITLE
Links to sourceforge wiki are broken 

### ISSUE THREAD

**Issue by slacy** [linuxwacom/xf86-input-wacom#13]
In README, there is a link to: 

https://sourceforge.net/apps/mediawiki/linuxwacom/index.php?title=Category:HOWTO

But that URL 404's.

Additionally, the "correct" URL for the Sourceforge-hosted MediaWiki is:

http://linuxwacom.sourceforge.net/wiki/index.php/Main_Page

But that page appears nearly blank (MediaWiki title appears with no body) under Chrome Version 65.0.3325.124 on Ubuntu 16.04 

Moving over to 100% GitHub would be a good choice at this point.

**Comment by jigpu** [comment]
We're working on migration details behind the scenes. In the meantime, you can get a recent copy of most of the wiki pages here on Github. We copied over the most important pages a few months back thankfully...

**Comment by slacy** [comment]
Thanks!
