### ISSUE TITLE
If pan scrolling is used with relative mode, the mouse pointer "walks" out of the scrolled region

### ISSUE THREAD

**Issue by yump** [linuxwacom/xf86-input-wacom#139]
When panscroll is active, the cursor moves when the pen is lifted but not when the pen is down.  So when you lift the pen and return to the start position to scroll again, the cursor moves.  This quickly walks the cursor outside of the window you are trying to scroll, so the scroll events stop going to the right place.

To reproduce, configure as follows:

    #!/bin/sh

    stylus="Wacom Intuos S Pen stylus" # replace with your device 

    xinput set-mode "$stylus" RELATIVE
    xsetwacom set "$stylus" Button 2 pan
    xsetwacom set "$stylus" PanscrollThreshold 50

Then hold down the pan button and attempt to scroll several times in the same direction on one window.

The problem is probably more noticeable if your environment uses focus-follows-mouse like mine, but I think web browsers and maybe other applications use mouse position to determine scroll focus for their internal scrollable elements.

**Comment by Greenscreener** [comment]
I have exactly the same problem! This is really annoying.
