### ISSUE TITLE
CTL-4100 (Wacom Intuos S) Eraser Button Mapping Help

### ISSUE THREAD

**Issue by JCRaymond** [linuxwacom/xf86-input-wacom#142]
For admins, this is a question, not an issue (at least I don't believe it is).

I have a windows drawing program (Leonardo) working in linux through wine (fairly well, I've had little to no issues so far), however I am unable to get the eraser to work.

In windows, the buttons can be specifically set to enable eraser mode, which just worked with Leonardo without any internal configuration. Is it possible to set one of the buttons to do this (with xsetwacom or something else)? Within Leonardo, there is the ability to set what middle/right click does, but setting either to the eraser does nothing (even with a mouse), so it almost seems like it's expecting something from the pen itself to tell it that it's in eraser mode. I'm not sure how, but at some point, the pen was stuck in eraser mode in Leonardo (the tools disappear and a picture of a pen appears whenever the eraser button is pressed in windows, and the same thing was happening), so it feels like there should be some way to get it working.

I also messed around a bit with xbindkeys (using xsetwacom to bind the side buttons on the pen to mouse button 40 so it wouldn't cause any weird interactions), however Leonardo was acting weird when I was trying to key presses. Something I wanted to try, but couldn't figure out, was to trigger a script that would disable the stylus, and make my pen permanently in eraser mode (and another to switch it back). Since I can trigger different scripts with xbindkeys based on when I click vs let go of the button, I think this would work. I just couldn't figure out how to disable the stylus input alone, and force the pen to behave like the eraser (using xinput disable on the eraser input disables both).

I'm sure my problem has something to do with the fact everything is running through wine, however I figured since I've been banging my head against this for a while I would ask here. Ideally, I could just make the side button switch to the eraser mode (like you can do in windows), but I figure this isn't an option.

**Comment by Pinglinux** [comment]
Please refer to #209. Basically, we can't map a stylus button to an eraser since they are on two different tools.
