### ISSUE TITLE
Wacom DTH 1152 touchscreen not working in Ubuntu 20.04

### ISSUE THREAD

**Issue by ekaveeramaths** [linuxwacom/xf86-input-wacom#149]
I have connected my Interactive Wacom pen tablet DTH 1152 to Ubuntu. I can see the screen of my Ubuntu home page, but touchscreen is not working, i am unable to use pen on my wacom tablet. Please give me a solution.

**Comment by jigpu** [comment]
Hi, please run our [sysinfo.sh script](https://raw.githubusercontent.com/linuxwacom/wacom-hid-descriptors/master/scripts/sysinfo.sh) and attach the generated tarball here.

**Comment by mperreau** [comment]
I have the same issue

**Comment by jigpu** [comment]
@mperreau same request as above: please run and attach the output from our sysinfo script. This will give us more information about what devices the system sees and any errors that might have been logged.

**Comment by mperreau** [comment]
Thanks, here it is
[sysinfo.JLyJ43Fybs.tar.gz](https://github.com/linuxwacom/xf86-input-wacom/files/5863134/sysinfo.JLyJ43Fybs.tar.gz)

**Comment by jigpu** [comment]
Thanks. Can you confirm if the tablet was connected when you ran the script? I don't see any indication of a Wacom device at all; not even an informational message from the kernel that it had detected a USB device...

**Comment by mperreau** [comment]
Yes, the tablet was connect by USB port (the bluetooth recognizes the presence of the tablet but cannot connect to it)

**Comment by jigpu** [comment]
Can you please disconnect the tablet, reboot, connect the tablet, wait 30 seconds, and then run the following two commands:
~~~
dmesg > dmesg.txt
cat /proc/uptime
~~~
Afterwards, attach the dmesg in a reply and let me know what the output from the second command was.

**Comment by mperreau** [comment]
[dmesg.txt](https://github.com/linuxwacom/xf86-input-wacom/files/5973571/dmesg.txt)
Here is the dmesg.txt
and the result of cat /proc/uptime is:
385257.66 589958.80
Thanks for your help
Michel

**Comment by mperreau** [comment]
Hi, everything is working now !
Since the upgrade to the distribution 20 I have not made anything else than the usual upgrade proposed by ubuntu, and now this seems to be a miracle, tablet is perfectly working.
Thanks again
Michel

**Comment by jigpu** [comment]
That's good news :smile:

I only see an Intuos tablet (CTL-6100WL) in your logs, not a DTH-1152 like the original poster. Can you confirm if that's the tablet you were trying to get connected? I can't think of much that would have changed recently to affect it, but hopefully whatever changed is a permanent fix for you :)

**Comment by mperreau** [comment]
Yes I have not changed my tablet, Sorry, I aw that somebody had a problem with "a" wacom tablet after upgrading ubuntu and so I asked help without looking to the model of tablet.
Anyway I confirm anything works fine presently. I am using it without problem.
Thanks
