### ISSUE TITLE
Wacom stylus shows two mouse pointers

### ISSUE THREAD

**Issue by Eshan-Agarwal** [linuxwacom/xf86-input-wacom#160]
I brought Wacom CTL 4100 and I am using ubuntu 20.04 LTS. I just plugged in a tablet and it works fine but then I search for its drivers also and follow Wacom project instructions, like input-Wacom, then also it works fine after sometimes later it works fine in android mode but does not work without android mode. Then I follow some secure boot tutorials and then everything works fine except it shows two mouse pointers. I follow [this](https://github.com/linuxwacom/input-wacom/wiki/Secure-Boot) tutorial on Creating and Registering Keys.

Please help !

**Comment by whot** [comment]
If you're running GNOME on Wayland, then it will create a separate cursor for the tablet device (that should disappear whenever you get out of proximity). That's by design, not a bug. Also, if you indeed are on Wayland, then you're not running the xf86-input-wacom driver :)
