### ISSUE TITLE
Problem using 'pan' command to scroll both up and down in cinnamon

### ISSUE THREAD

**Issue by ajP89** [linuxwacom/xf86-input-wacom#181]
OS: Manjaro linux 21.1.0 Pahvo
DE: Cinnamon
Tablet: Wacom One by Wacom S (CTL-472)
Issue: Using xsetwacom command, I used these commands to scroll pages using the lower button-- 
```
xsetwacom --set "Wacom One by Wacom S Pen stylus"  Button 2 "pan"
xsetwacom --set "Wacom One by Wacom S Pen stylus" "PanScrollThreshold" 200
```
I have not changed any other setting for the tablet. It is in absolute mode.

In cinnamon however, I can not scroll both ways. It is only in one direction (down). The graphics tablet utility has no option to set a button for pan. There is an option for 'no action' for the buttons but even then I can scroll only downwards. In window manager i3 on the same OS, the pan feature works normally bothways and I have no issue. Maybe the tablet utility is interfering in some way??

**Comment by Tobiaqs** [comment]
Some tips for configuring Easystroke with a drawing tablet. Start with no remaining xsetwacom config. I want to set the lower pen stylus button to trigger scrolling.

In preferences, set the gesture button as `(Instantly) Button 2` (choose Instant Gestures. Then press button 2 in the gray area)

Create an action. Set its type to Scroll. Record the stroke by simply tapping Button 2 (lower button on the pen).

Now you can scroll everywhere while holding the lower stylus button.
