### ISSUE TITLE
Cannot map all tablet buttons using xsetwacom

### ISSUE THREAD

**Issue by inmate4850** [linuxwacom/xf86-input-wacom#182]
OS: Linux mint mate
Tablet: Wacom Intuos Pen & Touch Small CTH-490

I found my specific tablet file in my system which outlines the buttons for it. The text file says "Top=A;B;C;D" which I assume can be mapped using buttons 1-4.

Example:

`xsetwacom --set "Wacom Intuos PT S 2 Pad pad" Button 1 key "u"`

Using this method I can only map buttons 1 and 3 but when I run the command for buttons 2 and 4 I don't get any errors. The command seems to run just fine but the buttons aren't actually getting mapped. I tried mapping other button numbers but no luck.

**Comment by Pinglinux** [comment]
What do you see by:

xsetwacom --get "Wacom Intuos PT S 2 Pad pad" Button 2
xsetwacom --get "Wacom Intuos PT S 2 Pad pad" Button 4

before and after you issue the set commands?

**Comment by inmate4850** [comment]
button +2
4

I actually tried running the --set command for button 4 again and this time it gave me the following error:

Unsupported offset into 'Wacom Button Actions' property.

**Comment by inmate4850** [comment]
I looked into the error and turns out the remaining buttons are 8 and 9. I've now mapped them and it seems to be working thus far, which is weird since I know I tried buttons 4-10 before with no errors.

Well, who cares, it works. Thanks for the help.
