### ISSUE TITLE
error: ‘KEY_ONSCREEN_KEYBOARD’ undeclared (first use in this function)  

### ISSUE THREAD

**Issue by zhangliyun9120** [linuxwacom/xf86-input-wacom#184]
when I complie the code, I got this error:
 ../src/wcmUSB.c:1644:8: error: ‘KEY_ONSCREEN_KEYBOARD’ undeclared (first use in this function)
   case KEY_ONSCREEN_KEYBOARD:

this made the result got build failed. can you solve it?

thank you.

my OS is ubuntu16.04

**Comment by zhangliyun9120** [comment]
please handle this issue ASAP, thank you so much!

**Comment by whot** [comment]
Closing, can't be that urgent after all...
