### ISSUE TITLE
Also interpolate pressure data 

### ISSUE THREAD

**Issue by rebuilder** [linuxwacom/xf86-input-wacom#187]
Some pens, like the Art Pen, do not send pressure readings as often as they do position readings. It seems the driver does not currently filter pressure, which maybe explains issues with pressure response with the Art Pen. Interpolating between pressure samples could help.

**Comment by jigpu** [comment]
For future reference, additional detail / screenshots can be found at https://www.reddit.com/r/wacom/comments/q3w9a4/mint_20_kde_neon_20_poor_stylus_sample_rate_on/

**Comment by whot** [comment]
Any chance we can get a `libinput record` for this? evtest recordings are notoriously hard to process in comparison.

**Comment by Pinglinux** [comment]
@rebuilder what kernel version do you use?
