### ISSUE TITLE
Keep the serial code alive?

### ISSUE THREAD

**Issue by whot** [linuxwacom/xf86-input-wacom#197]
I was reworking the driver a fair bit recently and I'm now wondering: is it worth keeping the ISDV4 serial backend alive? When was the last time Wacom released a compatible device for this code?

cc @Pinglinux, @jigpu

**Comment by Pinglinux** [comment]
We can remove the ISDV4 serial code. There is no new devices with serial connection. For users need the code for their old systems, they can always use the last xf86-inout-wacom before this release.

**Comment by whot** [comment]
It's not quite that easy, most users would use whatever the distros provide rather than self-compiling and while it was annoying to change for my patchset, the effort's been done. So keeping it doesn't matter too much in terms of maintenance but untested code is risky code.

So it's mostly a function of how old those devices are. I suspect by now they're all over a decade old? Do you remember the last time you released a device that was a serial one?

**Comment by Pinglinux** [comment]
June 2012 was the last time we discussed new serial device patches. I don't think we had other serial device after that.

**Comment by whot** [comment]
hmm, that's almost a decade, long enough I guess. I'd venture that most of those don't run the latest distributions anyway then. Thanks!

**Comment by jigpu** [comment]
It looks like the ISDv4 code survived your series of pull requests. Should this issue be closed, or do we want to go through the effort of removing the code?

**Comment by whot** [comment]
It did survive but it's completely untested (unless you did test it) and my only laptop with a serial device no longer boots. I'll send a PR to remove it asap.
