### ISSUE TITLE
Which interactive pen display drawing tablet should I get ?

### ISSUE THREAD

**Issue by yelai995** [linuxwacom/xf86-input-wacom#24]
Hello, so after realizing I have atrocious allergies I've decided to opt for a drawing tablet instead of a 2-in-1. At the moment I've seen a lot of positive reports on the XP-Pen Artist 22E Pro, but at the same time (having no way to test them in person) I am unsure if I should get the Huion, or save up the extra 500-700 pounds to purchase a Wacom Cintiq 22HD. At the moment I am more of a hobbyist than a professional illustrator, but do highly prefer paying a little extra for more reliability/longevity. Also less headache when finishing up a scanned sketch IE expecting the line to be in one place, but having it appear in another. I was considering the Artist 22E Pro as well, however, I am more likely to upgrade my PC within the next 3 - 5 years, which would support USB-C/4K resolution.

1. What is your budget?

around £1000 . 

2. Any preference on screen resolution?

At least 1920x1080p

3. Do you require a pen? With or without pressure sensitivity? Do you prefer Wacom EMR, AES or N-trig?
See the above linked FAQ for guidance

Yes.

4. What size Tablet PC would you prefer?

Between 21.5 or larger.

5. What will be the primary usage scenario of this tablet? (Email/Web Surfing/Drawing/Word Processing/Entertainment/Notetaking etc)

Illustration

6. What software and tasks do you intend to run? (Microsoft Office or other Word Processing Suite/Photoshop/3D Studio Max/Autocad etc)

Manga Studio, Photoshop, Adobe Illustrate.

XP-Pen is currently running a sale on their Artist 22E Pro for about £500 on Amazon UK : ( https://www.amazon.co.uk/Artist22E-Graphic-Interactive-Shortcut-Adjustable/dp/B01M28DHOA ). it seems to have the best screen.Also, between the XP-Pen Artist 22E Pro and Wacom Cintiq 22HD, which would you recommend? The XP-Pen Artist 22E Pro is £1000 cheaper than the Wacom Cintiq 22HD here, I want to know if the XP-Pen is as good or hopefully better than the Cintiq , especially the color accuracy of the display and accuracy of the pen.

**Comment by jigpu** [comment]
Hi there! We don't have any experience with the XP-Pen tablets so its difficult for us to recommend it for use with Linux. Looking at the [DIGImend project's supported tablet list](https://digimend.github.io/tablets/), the Artist 22E Pro isn't listed, and none of the Artist-series devices that are listed are marked as supported. You could, however, check with the DIGImend developers to get an idea of how difficult it would likely be to add support for that tablet.

The Cintiq 22 is well supported by our kernel and Xorg drivers and shouldn't give you any particular problems. The GNOME and KDE control panels should recognize the tablet and allow you to configure it to your liking. For other desktops, our command-line based `xsetwacom` utility can be used to change button settings.

Outside of Linux support, you should be able to find more detailed product information and reviews for both the XP-Pen and Wacom tablets elsewhere. If you have specific questions about the Linux driver, please let us know.
