### ISSUE TITLE
How do you speicify polling rate?

### ISSUE THREAD

**Issue by HaloHD** [linuxwacom/xf86-input-wacom#25]
I haven't found a way to specify polling rate within the files of this project or anywhere else for wacom drivers,
Arch Linux is my current OS.

**Comment by jigpu** [comment]
Our kernel and X11 drivers do not use polling to keep updated. At the lowest level, the USB transport itself will [poll the device](https://stackoverflow.com/a/4813541) to see if any updates are available, but on my (Arch Linux) PC at least, the kernel is already polling at its maximum rate (1000 Hz) despite devices only sending updates at a rate of ~133 Hz. You can check the polling rate of any attached tablets on your system by running `sudo awk -vRS= -vFS='\n' '/056a/ {print $0 "\n"}' /sys/kernel/debug/usb/devices` and looking for e.g. "Ivl=1ms" (which means a 1ms polling interval). You could potentially see if there are tricks to increase the poling rate for the USB subsytem, but it won't be anything tablet-specific.
