### ISSUE TITLE
No more 2 fingers right-click.

### ISSUE THREAD

**Issue by dodisoft** [linuxwacom/xf86-input-wacom#262]
Hello, 
I'm experimenting this little annoyance on my system which is described below:
debian bookworm kernel 5.16.0-6-amd64 under LXDE desktop.
My tablet is a Wacom Bamboo Fun CTH-661 (ID 056a:00d3)
Its driver: xf86-input-wacom 1.0.0-3

I guess from the day I updated this driver, I lost the ability to right-click with two fingers.
I dug through the posts from this forum concerning this issue, and tested some of the proposed ways to solve or workaround it, but nothing cured this failure today.

I triturated the TapTime parameter and some others in vain;
I just noticed that xev could'nt detect any 2fg-right-click...

As for now, I set a button to right-click, but feel somewhat frustrated to loose the former behaviour.
Anyway, thank you for your job. I stay tuned if I may help.
Dodic
____
Edit : July, 24 2022
Kernel moved to Linux 5.18.0-2-amd64
Driver updated to xf86-input-wacom (1.1.0-1)
As for today, nothing changed to this trouble. 
I didn't investigate much further without help: I only gathered a libinput debug-events that confirm the non-existence of a "second-finger-tap".
I also noticed that my two-fingers scrolling were sometimes getting wacky, as if scroll and pinch were mistaken.
I finally reversed to the bullseye version of xserver-xorg-input-wacom (0.34.99.1-1+b1), and recovered a perfectly functioning device.

Hoping those clues may help recovering my original tablet behaviour... 
Have a nice day !

**Comment by Pinglinux** [comment]
This issue was reported in #103. Let's track the progress there.
