### ISSUE TITLE
Add an option to a mouse mode

### ISSUE THREAD

**Issue by mhalano** [linuxwacom/xf86-input-wacom#267]
Windows software has a mouse mode available. I think we could implement a mouse mode as well, and maybe it can be available easily using the interface (GNOME and KDE). What do you think?

**Comment by whot** [comment]
Can you please specify what you mean exactly by "mouse mode"?

**Comment by mhalano** [comment]
There is an excerpt of documentation [here](https://101.wacom.com/UserHelp/en/MappingMouseMode.htm)

**Comment by Pinglinux** [comment]
@mhalano That's already supported in Gnome Control Center through "Wacom Tablet" settings and xsetwacom through
                      Mode             - Switches cursor movement mode (default is absolute)
You need to set the tool in relative mode if xsetwacom works for you or set "Tracking Mode" to Touchpad (relative) in Gnome Wacom Tablet.
