### ISSUE TITLE
generate full xorg config with --xconf

### ISSUE THREAD

**Issue by petaflot** [linuxwacom/xf86-input-wacom#331]
quit disappointed that `--xconf` flag does not generate the full config[^1], including values shown below and specifically `idevnane` and `devpath`
```
Section "InputDevice"
  Identifier "idevname"
  Driver "wacom"
  Option "Device"   "devpath"
  ...
EndSection
```

furthermore, [^1] specifies quite a number of options that are absent from `xsetwacom -x` output. is it on purpose?

[ ^1]: https://xorg.freedesktop.org/releases/X11R6.9.0/doc/html/wacom.4.html

**Comment by whot** [comment]
Going to add an extra note here: adding all possible options with their default values is IMO bad practice and increases the workload on maintainers if something goes wrong. First, this means that any upstream default option changes never make it through to the user without them updating the config file. We don't change defaults very often so when we do it's usually for good reasons.

Second, unless the user puts the effort in during reporting it can be impossible to say for us which of the 50 options listed in the config file was changed on purpose and which one was just dumped there from some old version of the driver.

Overall, I think our man page is detailed enough that adding the options that matter is largely an exercise in copy/paste, having xsetwacom spit out a config with all options is counterproductive.
