### ISSUE TITLE
absolute mode tweak

### ISSUE THREAD

**Issue by petaflot** [linuxwacom/xf86-input-wacom#332]
forgive the lame title, I lack the words to express in a short form what I am trying to achieve. suggestions welcome.

I have a (non-graphic) tablet with an active area of 152x95mm (1.6 aspect ratio) and a triple-head display (5.333 aspect ratio). When I use the tablet, it's limited to a portion of a single screen.

What I'd like to achieve is have a ~1:1 match between the stylus motion and the pointer motion on screen, limited to a very specific portion of my display. 

* coordinates should be absolute.
* the portion of the display can be set with a command, eventually with a graphic helper to show the boundary (this can be permanent as long as the tablet is in use and may include dimensional helpers such as dots, a grid.. basically a PNG texture with transparency that remains in the foreground, above all windows and does not grab focus)
* preferably with a pointer that is specific to the tablet/stylus (distinct from regular mouse pointer that is relative and bounded by the size of the display)

so.. is there a way to rapidly achieve at least part of the above?

thanks

**Comment by jigpu** [comment]
TeX source has been replaced with SVG images
