### ISSUE TITLE
Remove old detritus from the man page

### ISSUE THREAD

**Issue by whot** [linuxwacom/xf86-input-wacom#339]
Low-hanging fruit if someone finds the time: the initial parts of the wacom man page are effectively a decade out of date. We don't recommed using `Section InputDevice` anymore, disabling hotplugging is so niche it's not worth mentioning, etc.

**Comment by flying-elephant** [comment]
@whot 
Hi,
I'm working on your request currently and I'd like to make sure before proceeding it.
Do you suppose all of the descriptions related to InputDevice section deleted such as all of the options?
I'd like to make sure of it.

**Comment by whot** [comment]
basically: `Section InputDevice` should be `Section InputClass` with the corresponding examples. The whole driver-internal device hotplugging section needs a rework: `inputclass` and input device hotplugging have been the default for 15 or so years now, so we should default to explaining this.

The actual options should be left alone, unless they don't really matter anymore.
