### ISSUE TITLE
Variation of Installation Instructions for Debian/Ubuntu

### ISSUE THREAD

**Issue by martinomburajr** [linuxwacom/xf86-input-wacom#55]
Installation for Ubuntu/Debian documentation can read

`sudo apt-get update && sudo apt-get install xserver-xorg-input-wacom`

Otherwise one may get the following
`/bin/bash: apt-get update && apt-get install xserver-xorg-input-wacom: command not found
`

**Comment by jigpu** [comment]
What version of Ubuntu or Debian are you using? I can't think of any reason that you'd get a `command not found` error with the `sudo -s` version of the command but not the proposed version.

**Comment by martinomburajr** [comment]
Hello @jigpu , Sorry was away for a bit.

This is the error I get when running the  ` sudo -s 'apt-get update && apt-get install xserver-xorg-input-wacom'` command

![image](https://user-images.githubusercontent.com/8682597/56453065-f7048680-633b-11e9-9e66-655d4821e4e1.png)

**Comment by jigpu** [comment]
Thanks. What version of Ubuntu or Debian are you using?

**Comment by jigpu** [comment]
Closing. Feel free to re-open with the necessary information.
