### ISSUE TITLE
Wacom Bamboo 16FG on Ubuntu didn't expose Pressure event to Chromium or Firefox 

### ISSUE THREAD

**Issue by simon0356** [linuxwacom/xf86-input-wacom#60]
Hello,

I currently try to get the javascript PointerEvent.pressure event working with Wacom device (Wacom Bamboo 16FG) on Chromium/Firefox Linux Ubuntu 18.04.

Using the same Wacom tablet on windows 10 and recent version of chromium I can get the pressure event working.

Did you manage to get this Javascript feature working on a Linux web browser ?

Thanks
Simon Tropée

**Comment by jigpu** [comment]
Last I checked (a few years ago), Firefox was not reading pressure data from our driver. This may have changed, however. I would check [Firefox bug 822898 "[meta] Implement pointer events"](https://bugzilla.mozilla.org/show_bug.cgi?id=822898) and see what the status of pointer events on Linux is.
