### ISSUE TITLE
Hope can drive Wacom DTI-520

### ISSUE THREAD

**Issue by SenlinOS** [linuxwacom/xf86-input-wacom#7]
I have a Wacom DTI-520, the old LCD tablet.
Cannot drive in Ubuntu 16.04.

[   528.461] (II) config/udev: Adding input device WACOM DTI-520-U Pen (/dev/input/event7)
[   528.461] (  ) WACOM DTI-520-U Pen: Applying InputClass "Wacom USB device class"
[   528.461] (  ) WACOM DTI-520-U Pen: Applying InputClass "Wacom class"
[   528.461] (II) Using input driver 'wacom' for 'WACOM DTI-520-U Pen'
[   528.461] (  ) WACOM DTI-520-U Pen: always reports core events
[   528.461] (  ) Option "Device" "/dev/input/event7"
[   528.528] (EE) WACOM DTI-520-U Pen: Invalid type 'stylus' for this device.
[   528.528] (EE) WACOM DTI-520-U Pen: Invalid type 'eraser' for this device.
[   528.528] (EE) WACOM DTI-520-U Pen: Invalid type 'cursor' for this device.
[   528.528] (EE) WACOM DTI-520-U Pen: Invalid type 'touch' for this device.
[   528.528] (EE) WACOM DTI-520-U Pen: Invalid type 'pad' for this device.
[   528.528] (EE) WACOM DTI-520-U Pen: No type specified
[   528.560] (EE) PreInit returned 8 for "WACOM DTI-520-U Pen"
[   528.560] (II) UnloadModule: "wacom"

A device, actually has two ID.
$ lsusb
Bus 001 Device 010: ID 056a:003a Wacom Co., Ltd 
Bus 001 Device 009: ID 056a:003b Wacom Co., Ltd 

Thank you.

**Comment by jigpu** [comment]
This issue was moved to linuxwacom/input-wacom#17
