### ISSUE TITLE
Changing settings on Eraser affects Tip as well

### ISSUE THREAD

**Issue by paulrattu** [linuxwacom/xf86-input-wacom#76]
In the Wacom Tablet settings in gnome, changing the Eraser Pressure Feel slider makes no difference to either the Eraser but changing the Tip Pressure Feel changes both the Eraser and Tip. I've also noticed the same thing when changing the Threshold setting in xsetwacom, where changing the Threshold for Eraser will change both Eraser and Tip.

**Comment by jigpu** [comment]
I thought the pressure feel issue had already been reported to GNOME, but I can't seem to find it anymore. Please file a bug at https://gitlab.gnome.org/GNOME/gnome-control-center/issues to let them know about the issue.

As for the threshold issue, it appears that the observed behavior is actually how the feature was written. At the *very* least this should be documented, but I strongly suspect the behavior should actually be changed. For future reference, could you explain a little why/how you would use different thresholds for eraser and tip?

**Comment by paulrattu** [comment]
This was really a one off issue for one particular user, if having the threshold be the same for both eraser and tip is by design then that's fine.

**Comment by Pinglinux** [comment]
Yes, we assumed that people would have like the same pressure sensitivity for both tip and eraser since they are on the same tool.
