### ISSUE TITLE
Hover click Option in xorg.conf.d

### ISSUE THREAD

**Issue by nuggattiStar** [linuxwacom/xf86-input-wacom#82]
Hi, does anyone know if it's possible to set this in xorg.conf.d?
I am currently running this through a shell script but would love  to have it trigger everytime I plug in the tablet.
$xinput set-prop "Wacom Tablet name" "Wacom Hover Click" "0"

**Comment by jigpu** [comment]
Adding the following line to your xorg.conf.d file should have the same effect:
~~~
Option "TPCButton" "on"
~~~

**Comment by nuggattiStar** [comment]
Thanks, that works like a charm! I see now in hindsight that I should have perused the man page a little better.. oh well :P Thanks again.
