### ISSUE TITLE
device id's change and are not consistent.

### ISSUE THREAD

**Issue by queglay** [linuxwacom/xf86-input-wacom#98]
If I plugin the wacom intuos pen pro, get the device list, unplug and plug in again, the device id's are different.  This makes management a little hacky for me, unless I could specify id by name instead of number.

Here is an example-
```
[deadlineuser@workstation wacom-config]$ xsetwacom --list devices
Wacom Intuos Pro L Finger touch 	id: 12	type: TOUCH     
Wacom Intuos Pro L Pen stylus   	id: 13	type: STYLUS    
Wacom Intuos Pro L Pen eraser   	id: 14	type: ERASER    
Wacom Intuos Pro L Pen cursor   	id: 15	type: CURSOR    
Wacom Intuos Pro L Pad pad      	id: 16	type: PAD       
[deadlineuser@workstation wacom-config]$ xsetwacom --list devices
Wacom Intuos Pro L Pen stylus   	id: 12	type: STYLUS    
Wacom Intuos Pro L Pen eraser   	id: 13	type: ERASER    
Wacom Intuos Pro L Pen cursor   	id: 14	type: CURSOR    
Wacom Intuos Pro L Pad pad      	id: 15	type: PAD       
Wacom Intuos Pro L Finger touch 	id: 16	type: TOUCH  
```

**Comment by whot** [comment]
xsetwacom has supported using the device name instead of a numeric id since 2009 or so, so this should work - just make sure you quote the name properly.

Device IDs are assigned by the X server btw, the wacom driver cannot really do much about the number.
